### ISSUE TITLE
progressbar.widgets has no attribute FormatWidgetMixin

### ISSUE THREAD

**Issue by epifanio** [maartenbreddels/vaex#19]
Hi,

trying to run a pip installed `git:master` version i got the following `import error`:

```
epinux@epinux:~$ vaex
Traceback (most recent call last):
  File "/usr/local/bin/vaex", line 11, in <module>
    load_entry_point('vaex==1.0.0b6', 'console_scripts', 'vaex')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/vaex/__init__.py", line 71, in <module>
    import vaex.dataset
  File "/usr/local/lib/python3.5/dist-packages/vaex/dataset.py", line 18, in <module>
    import vaex.utils
  File "/usr/local/lib/python3.5/dist-packages/vaex/utils.py", line 179, in <module>
    class CpuUsage(progressbar.widgets.FormatWidgetMixin, progressbar.widgets.TimeSensitiveWidgetBase):
AttributeError: module 'progressbar.widgets' has no attribute 'FormatWidgetMixin'
```

**Comment by maartenbreddels** [comment]
Are you sure you installed 'progressbar2'? It has the same package name as progressbar. Not sure how that can happen when you did pip install though.

**Comment by maartenbreddels** [comment]
indeed 👍
