### ISSUE TITLE
Syntax error with `pip install` on Python 3

### ISSUE THREAD

**Issue by gwerbin** [maartenbreddels/vaex#39]
```
$ pip3 install vaex
Collecting vaex
  Using cached vaex-0.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4j/n8nxnsy12y92t475g318yptm0000gn/T/pip-build-in7iizfc/vaex/setup.py", line 18
        print "Executing: ", cmd
                          ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
```

I don't get the error when installing from Git:

```
$ pip3 install git+https://github.com/maartenbreddels/vaex/
```

**Comment by maartenbreddels** [comment]
Hi, please see #36

**Comment by gwerbin** [comment]
I ended up installing from Conda. But the answer is to install with `--pre`?

**Comment by maartenbreddels** [comment]
indeed for now. Until I release a stable 1.0

**Comment by PriyaPareek635** [comment]
If you want to install any package or libraries using python 3.x then follow these steps:
1)go to cmd 
2)copy the path of python up to scripts for ex :(C:\Users\PriyaPareek\AppData\Local\Programs\Python\Python37-32\Scripts\)
3)press enter 
4)then install the package or library like this:      pip install SomePackage
