### ISSUE TITLE
ModuleNotFoundError: No module named 'vaex.ext.bqplot'

### ISSUE THREAD

**Issue by tigikay** [maartenbreddels/vaex#66]
Just started using vaex, trying to 3d plot galaxy sim, 2D plots work. Installed bqplot seperately - still not recognised by vaex.

Full error is:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-1b6052421b12> in <module>()
----> 1 ds.plot3d(ds.x,ds.y,ds.z,f='log')

/usr/local/lib/python3.6/site-packages/vaex/dataset.py in plot3d(self, x, y, z, vx, vy, vz, vwhat, limits, grid, what, shape, selection, f, vcount_limits, smooth_pre, smooth_post, grid_limits, normalize, colormap, figure_key, fig, lighting, level, opacity, level_width, show, **kwargs)
   2464                show=True, **kwargs):
   2465         """Use at own risk, requires ipyvolume"""
-> 2466         import vaex.ext.ipyvolume
   2467         # vaex.ext.ipyvolume.
   2468         cls = vaex.ext.ipyvolume.PlotDefault

/usr/local/lib/python3.6/site-packages/vaex/ext/ipyvolume.py in <module>()
----> 1 from .bqplot import PlotBase
      2 import ipyvolume.pylab as p3
      3 import ipyvolume.examples
      4 import traitlets
      5 import vaex.dataset

ModuleNotFoundError: No module named 'vaex.ext.bqplot'

```

**Comment by maartenbreddels** [comment]
Hi,

does `ds.plot_widget('x', 'y')` work, after that try, `ds.plot_widget('x', 'y', 'z', backend='ipyvolume')`. I should fix plot3d, but meanwhile this should work.
What went wrong with conda btw, did it had sth to do with vaex?

cheers,

Maarten

**Comment by FavioVazquez** [comment]
Same problem here! Installed via Conda. Trying to use plot_bq

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report, I need to make plot_bq also backwards compatible, for now use `ds.plot_widget('x', 'y')`.

Regards,

Maarten

**Comment by rancdg** [comment]
Hi,
Thanks for creating and sharing this awesome framework! 
experiencing the same error with plot_bq, on both python 2.7 and 3.6 environments, built specifically for this (on a machine running ubuntu)
when trying to work with plot_widget i get-
"No module named 'vaex.jupyter'" on the 3.6 env
"No module named jupyter.plot" on the 2.7 env
both stemming from "import vaex.jupyter.plot" on dataframe.py

**Comment by mfouesneau** [comment]
```python
ds.plot_widget('x', 'y', 'z', backend='ipyvolume')

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-146-b71ac5f47cfb>", line 1, in <module>
    sds.plot_widget('x', 'y', 'z', what='mean(A0_p50)', backend='ipyvolume')

  File "/usr/local/lib/python3.8/site-packages/vaex/utils.py", line 57, in wraps2
    return f(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/vaex/dataframe.py", line 1698, in plot_widget
    return self.widget.heatmap(x, y, limits=limits, transform=f, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/vaex/jupyter/__init__.py", line 110, in heatmap
    x, y = self._axes([x, y], limits)

  File "/usr/local/lib/python3.8/site-packages/vaex/jupyter/__init__.py", line 73, in _axes
    limits = self.df.limits(expressions, limits)

  File "/usr/local/lib/python3.8/site-packages/vaex/dataframe.py", line 1595, in limits
    number = ast.literal_eval(number)

  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')

  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,

  File "<unknown>", line unknown
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by mfouesneau** [comment]
Any news on this?  vaexgui is unusable and beyond repair.
